name: Quality

on:
  pull_request:
    branches:
      - master
      - main
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Node.js
        uses: ./.github/workflows/setup-node

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

      - name: Audit
        run: npm audit
