name: Quality

on:
  pull_request:
    branches:
      - master
      - main
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup Node.js
        uses: ./.github/workflows/setup-node

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

      - name: Audit
        run: npm audit
