name: Quality

on:
  pull_request:
    branches:
      - master
      - main
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Node.js
        uses: ./.github/workflows/setup-node

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

      - name: Audit
        run: npm audit
